### ISSUE TITLE
Multiple databaseChangeLog subsystem configurations does not work

### ISSUE THREAD

**Issue by jamesnetherton** [jamesnetherton/wildfly-liquibase#17]
Change logs are currently executed concurrently by separate threads which leads to:

```
Caused by: java.lang.IllegalStateException: liquibase.exception.LockException: liquibase.exception.DatabaseException: Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.DATABASECHANGELOGLOCK(ID)"; SQL statement:
INSERT INTO PUBLIC.DATABASECHANGELOGLOCK (ID, LOCKED) VALUES (1, FALSE) [23505-193] [Failed SQL: INSERT INTO PUBLIC.DATABASECHANGELOGLOCK (ID, LOCKED) VALUES (1, FALSE)]
	at com.github.jamesnetherton.extension.liquibase.service.ChangeLogExecutionService.executeChangeLog(ChangeLogExecutionService.java:107)
	at com.github.jamesnetherton.extension.liquibase.service.ChangeLogExecutionService.start(ChangeLogExecutionService.java:72)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:2032)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1955)
	... 3 more
Caused by: liquibase.exception.LockException: liquibase.exception.DatabaseException: Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.DATABASECHANGELOGLOCK(ID)"; SQL statement:
INSERT INTO PUBLIC.DATABASECHANGELOGLOCK (ID, LOCKED) VALUES (1, FALSE) [23505-193] [Failed SQL: INSERT INTO PUBLIC.DATABASECHANGELOGLOCK (ID, LOCKED) VALUES (1, FALSE)]
	at liquibase.lockservice.StandardLockService.acquireLock(StandardLockService.java:242)
	at liquibase.lockservice.StandardLockService.waitForLock(StandardLockService.java:170)
	at liquibase.Liquibase.update(Liquibase.java:196)
	at liquibase.Liquibase.update(Liquibase.java:192)
	at com.github.jamesnetherton.extension.liquibase.service.ChangeLogExecutionService.executeChangeLog(ChangeLogExecutionService.java:101)
	... 6 more
```

**Comment by jamesnetherton** [comment]
This is only an issue when change logs are executed concurrently against the same database, which I'm not sure makes sense.
