### ISSUE TITLE
Scope & ScopeManager are not thread safe

### ISSUE THREAD

**Issue by jamesnetherton** [jamesnetherton/wildfly-liquibase#82]
When changelogs are being deployed concurrently, things start to go wrong in `Scope` & `ScopeManager`:

```
08:39:20,730 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-4) MSC000001: Failed to start service jboss.liquibase.changelog.execution."config2_1699799381-wildfly-liquibase-changelog.xml.1": org.jboss.msc.service.StartException in service jboss.liquibase.changelog.execution."config2_1699799381-wildfly-liquibase-changelog.xml.1": Failed to start service
	at org.jboss.msc@1.4.12.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1731)
	at org.jboss.msc@1.4.12.Final//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1559)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1363)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: liquibase.exception.LiquibaseException: java.lang.RuntimeException: Cannot end scope pprvjauqpv when currently at scope hxmlehfzkf
	at com.github.jamesnetherton.extension.liquibase@2.1.0-SNAPSHOT//com.github.jamesnetherton.extension.liquibase.service.ChangeLogExecutionService.executeChangeLog(ChangeLogExecutionService.java:96)
	at com.github.jamesnetherton.extension.liquibase@2.1.0-SNAPSHOT//com.github.jamesnetherton.extension.liquibase.service.ChangeLogExecutionService.start(ChangeLogExecutionService.java:62)
	at org.jboss.msc@1.4.12.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1739)
	at org.jboss.msc@1.4.12.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1701)
	... 6 more
Caused by: liquibase.exception.LiquibaseException: java.lang.RuntimeException: Cannot end scope pprvjauqpv when currently at scope hxmlehfzkf
	at org.liquibase.core@4.1.1//liquibase.Liquibase.runInScope(Liquibase.java:2282)
	at org.liquibase.core@4.1.1//liquibase.Liquibase.update(Liquibase.java:215)
	at org.liquibase.core@4.1.1//liquibase.Liquibase.update(Liquibase.java:201)
	at com.github.jamesnetherton.extension.liquibase@2.1.0-SNAPSHOT//com.github.jamesnetherton.extension.liquibase.service.ChangeLogExecutionService.executeChangeLog(ChangeLogExecutionService.java:93)
	... 9 more
Caused by: java.lang.RuntimeException: Cannot end scope pprvjauqpv when currently at scope hxmlehfzkf
	at org.liquibase.core@4.1.1//liquibase.Scope.exit(Scope.java:209)
	at org.liquibase.core@4.1.1//liquibase.Scope.child(Scope.java:171)
	at org.liquibase.core@4.1.1//liquibase.Scope.child(Scope.java:159)
	at org.liquibase.core@4.1.1//liquibase.Scope.child(Scope.java:138)
	at org.liquibase.core@4.1.1//liquibase.Liquibase.runInScope(Liquibase.java:2277)
	... 12 more
```

**Comment by poznas** [comment]
Hi James, have you reported this problem to [liquibase](https://github.com/liquibase/liquibase) team?

**Comment by jamesnetherton** [comment]
Hello - I've not reported anything yet. I wanted to find the time to dig into the problem a bit more before doing that. The default implementation in Liquibase relies on statically scoped singletons, which tend not to play well in containers like WildFly.

It could probably be worked around here with a custom Scope that can handle concurrency a bit better.

But, I wonder if allowing a deployment to contain multiple changelogs for different datasources is actually a good idea. Maybe I should have enforced that you need to create a separate deployment for that scenario.
